execution:
#  command_executor_factory: com.outbrain.gomjabbar.execution.RundeckCommandExecutor
  command_executor_factory: com.outbrain.gomjabbar.execution.AnsibleCommandExecutor

filters:
  clusters:
    include:
    # a list of clusters to be included in the targets
    # if empty, all non excluded clusters are included
    exclude:
    # a list of clusters to be excluded from the targets (can be empty)

  modules:
    include:
    # a list of modules to be included in the targets
    # if empty, all non excluded modules are included
    exclude:
    # a list of modules to be excluded from the targets (can be empty)

  tags:
    include:
    # a list of tags targets must have to be included in the targets
    # if empty, only excluded tags are considered.
    # example:
    #- production
    #- safe-for-chaos
    exclude:
    # a list of tags used for excluding targets containing these tags (can be empty)

commands:
  harmless_remote_command:
    description: "Runs a harmless shell command on remote targets - should take about 5 sec to complete"
    fail: "echo 'homeDir=${user.dir} module=${module} host=${host}'; for i in `seq 1 5`; do echo $i; sleep 1; done\n"
    revert: "echo 'reverted'"

  graceful_shutdown:
    description: "Gracefully shuts down services using init.d"
    fail: "sudo service ${module} stop"
    revert: "sudo service ${module} start"

  graceless_shutdown:
    description: "Brutally kills service instances"
    fail: "sudo pkill -9 -f ${module}"
    revert: "sudo service ${module} start"

  traffic_controller:
    description: "Introduces high latency, and packet loss"
    fail: "DEV=`sudo route | grep default | awk \"'{print $NF}'\"`; sudo tc qdisc add dev $DEV root netem delay 300ms loss 5%; sudo tc -s qdisc"
    revert: "sudo tc qdisc del dev `route | grep default | awk \"'{print $NF}'`\" root; sudo tc -s qdisc"

#scripts:
#  My_Fault_Script:
#    description: "Fails stuff"
#    fail:
#      URL: "http://my.script.com/script.sh"
#      args: "-f foo -b bar"
#    revert:
#      URL: "http://my.script.com/script.sh"
#      args: "-revert"
